// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

/**
 * APIResult 是 opencode serve API 的透传结果。
 */
export class APIResult {
    /**
     * Creates a new APIResult instance.
     * @param {Partial<APIResult>} [$$source = {}] - The source object to create the APIResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["status"] = 0;
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new APIResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {APIResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new APIResult(/** @type {Partial<APIResult>} */($$parsedSource));
    }
}

/**
 * CmdGroup 命令分组。
 */
export class CmdGroup {
    /**
     * Creates a new CmdGroup instance.
     * @param {Partial<CmdGroup>} [$$source = {}] - The source object to create the CmdGroup.
     */
    constructor($$source = {}) {
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("cmds" in $$source)) {
            /**
             * @member
             * @type {CmdInfo[]}
             */
            this["cmds"] = [];
        }
        if (!("isTui" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isTui"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CmdGroup instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CmdGroup}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("cmds" in $$parsedSource) {
            $$parsedSource["cmds"] = $$createField1_0($$parsedSource["cmds"]);
        }
        return new CmdGroup(/** @type {Partial<CmdGroup>} */($$parsedSource));
    }
}

/**
 * CmdInfo 命令展示信息。
 */
export class CmdInfo {
    /**
     * Creates a new CmdInfo instance.
     * @param {Partial<CmdInfo>} [$$source = {}] - The source object to create the CmdInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("sub" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sub"] = "";
        }
        if (!("options" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["options"] = "";
        }
        if (!("desc" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["desc"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CmdInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CmdInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CmdInfo(/** @type {Partial<CmdInfo>} */($$parsedSource));
    }
}

/**
 * CmdPaletteItem 命令面板展示项。
 */
export class CmdPaletteItem {
    /**
     * Creates a new CmdPaletteItem instance.
     * @param {Partial<CmdPaletteItem>} [$$source = {}] - The source object to create the CmdPaletteItem.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CmdPaletteItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CmdPaletteItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CmdPaletteItem(/** @type {Partial<CmdPaletteItem>} */($$parsedSource));
    }
}

/**
 * ModelEntry 前端展示用的模型条目。
 */
export class ModelEntry {
    /**
     * Creates a new ModelEntry instance.
     * @param {Partial<ModelEntry>} [$$source = {}] - The source object to create the ModelEntry.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("comment" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["comment"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModelEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelEntry(/** @type {Partial<ModelEntry>} */($$parsedSource));
    }
}

/**
 * ModelInfo 前端展示用模型信息。
 */
export class ModelInfo {
    /**
     * Creates a new ModelInfo instance.
     * @param {Partial<ModelInfo>} [$$source = {}] - The source object to create the ModelInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModelInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelInfo(/** @type {Partial<ModelInfo>} */($$parsedSource));
    }
}

/**
 * ModelSaveResult 模型保存结果。
 */
export class ModelSaveResult {
    /**
     * Creates a new ModelSaveResult instance.
     * @param {Partial<ModelSaveResult>} [$$source = {}] - The source object to create the ModelSaveResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelSaveResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModelSaveResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelSaveResult(/** @type {Partial<ModelSaveResult>} */($$parsedSource));
    }
}

/**
 * ProviderInfo 前端展示用供应商信息。
 */
export class ProviderInfo {
    /**
     * Creates a new ProviderInfo instance.
     * @param {Partial<ProviderInfo>} [$$source = {}] - The source object to create the ProviderInfo.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("baseURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["baseURL"] = "";
        }
        if (!("apiKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["apiKey"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("models" in $$source)) {
            /**
             * @member
             * @type {ModelInfo[]}
             */
            this["models"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProviderInfo}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField5_0($$parsedSource["models"]);
        }
        return new ProviderInfo(/** @type {Partial<ProviderInfo>} */($$parsedSource));
    }
}

/**
 * ProviderSave 前端提交的供应商保存数据。
 */
export class ProviderSave {
    /**
     * Creates a new ProviderSave instance.
     * @param {Partial<ProviderSave>} [$$source = {}] - The source object to create the ProviderSave.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("baseURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["baseURL"] = "";
        }
        if (!("apiKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["apiKey"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("models" in $$source)) {
            /**
             * @member
             * @type {ModelInfo[]}
             */
            this["models"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderSave instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProviderSave}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField5_0($$parsedSource["models"]);
        }
        return new ProviderSave(/** @type {Partial<ProviderSave>} */($$parsedSource));
    }
}

/**
 * ProxyConfig 是启动 opencode serve 时注入的代理配置。
 */
export class ProxyConfig {
    /**
     * Creates a new ProxyConfig instance.
     * @param {Partial<ProxyConfig>} [$$source = {}] - The source object to create the ProxyConfig.
     */
    constructor($$source = {}) {
        if (!("proxyEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["proxyEnabled"] = false;
        }
        if (!("proxyHost" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["proxyHost"] = "";
        }
        if (!("proxyPort" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["proxyPort"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxyConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProxyConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProxyConfig(/** @type {Partial<ProxyConfig>} */($$parsedSource));
    }
}

/**
 * SaveResult 保存操作结果。
 */
export class SaveResult {
    /**
     * Creates a new SaveResult instance.
     * @param {Partial<SaveResult>} [$$source = {}] - The source object to create the SaveResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SaveResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SaveResult(/** @type {Partial<SaveResult>} */($$parsedSource));
    }
}

/**
 * SessionInfo 会话记录。
 */
export class SessionInfo {
    /**
     * Creates a new SessionInfo instance.
     * @param {Partial<SessionInfo>} [$$source = {}] - The source object to create the SessionInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionInfo(/** @type {Partial<SessionInfo>} */($$parsedSource));
    }
}

/**
 * SkillInfo 技能信息。
 */
export class SkillInfo {
    /**
     * Creates a new SkillInfo instance.
     * @param {Partial<SkillInfo>} [$$source = {}] - The source object to create the SkillInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("linked" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["linked"] = false;
        }
        if (!("source" in $$source)) {
            /**
             * "global" 或 "project"
             * @member
             * @type {string}
             */
            this["source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SkillInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SkillInfo(/** @type {Partial<SkillInfo>} */($$parsedSource));
    }
}

/**
 * Stats 统计信息。
 */
export class Stats {
    /**
     * Creates a new Stats instance.
     * @param {Partial<Stats>} [$$source = {}] - The source object to create the Stats.
     */
    constructor($$source = {}) {
        if (!("globalSkills" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["globalSkills"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Stats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Stats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Stats(/** @type {Partial<Stats>} */($$parsedSource));
    }
}

/**
 * ToggleResult 单个技能切换结果。
 */
export class ToggleResult {
    /**
     * Creates a new ToggleResult instance.
     * @param {Partial<ToggleResult>} [$$source = {}] - The source object to create the ToggleResult.
     */
    constructor($$source = {}) {
        if (!("skillName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["skillName"] = "";
        }
        if (!("linked" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["linked"] = false;
        }
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToggleResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ToggleResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToggleResult(/** @type {Partial<ToggleResult>} */($$parsedSource));
    }
}

/**
 * WebResult 前端展示用的 web 状态。
 */
export class WebResult {
    /**
     * Creates a new WebResult instance.
     * @param {Partial<WebResult>} [$$source = {}] - The source object to create the WebResult.
     */
    constructor($$source = {}) {
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("health" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["health"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WebResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WebResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WebResult(/** @type {Partial<WebResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = CmdInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = ModelInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
