// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App 是 Wails 应用的核心结构体，所有绑定到前端的方法都定义在此。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "./model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddModelEntry 添加 agent 或 category 条目。
 * @param {string} key
 * @param {string} modelName
 * @param {string} entryType
 * @returns {$CancellablePromise<model$0.ModelSaveResult>}
 */
export function AddModelEntry(key, modelName, entryType) {
    return $Call.ByID(4280326103, key, modelName, entryType).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * AddModelType 添加模型配置类型分组。
 * @param {string} entryType
 * @returns {$CancellablePromise<model$0.ModelSaveResult>}
 */
export function AddModelType(entryType) {
    return $Call.ByID(162494865, entryType).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * AnswerQuestion 回答 question 工具调用。
 * @param {string} sessionID
 * @param {string} answerLabel
 * @returns {$CancellablePromise<model$0.APIResult>}
 */
export function AnswerQuestion(sessionID, answerLabel) {
    return $Call.ByID(910414563, sessionID, answerLabel).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CreateSession 使用指定工作目录创建新会话。
 * @param {string} workDir
 * @returns {$CancellablePromise<model$0.APIResult>}
 */
export function CreateSession(workDir) {
    return $Call.ByID(2952361431, workDir).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * DeleteModelEntry 删除 agent 或 category 条目。
 * @param {string} key
 * @param {string} entryType
 * @returns {$CancellablePromise<model$0.ModelSaveResult>}
 */
export function DeleteModelEntry(key, entryType) {
    return $Call.ByID(962368617, key, entryType).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * DeleteModelType 删除整个模型配置类型分组。
 * @param {string} entryType
 * @returns {$CancellablePromise<model$0.ModelSaveResult>}
 */
export function DeleteModelType(entryType) {
    return $Call.ByID(4233224839, entryType).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * DeleteProvider 删除供应商。
 * @param {string} key
 * @returns {$CancellablePromise<model$0.SaveResult>}
 */
export function DeleteProvider(key) {
    return $Call.ByID(3297626303, key).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetAvailableModels 通过 opencode models 获取所有可用模型。
 * @returns {$CancellablePromise<string[]>}
 */
export function GetAvailableModels() {
    return $Call.ByID(2005304584).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetCommands 返回所有常用命令分组数据
 * @returns {$CancellablePromise<$models.CmdGroup[]>}
 */
export function GetCommands() {
    return $Call.ByID(983453965).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetConfigPath 返回模型配置文件路径。
 * @returns {$CancellablePromise<string>}
 */
export function GetConfigPath() {
    return $Call.ByID(4029735838);
}

/**
 * GetFullConfig 返回完整 JSONC 字符串。
 * @returns {$CancellablePromise<string>}
 */
export function GetFullConfig() {
    return $Call.ByID(1478138180);
}

/**
 * GetModelConfig 读取所有 agent/category 的模型配置。
 * @returns {$CancellablePromise<model$0.ModelEntry[]>}
 */
export function GetModelConfig() {
    return $Call.ByID(1396865434).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetOpenCodeCommands 从 opencode serve 获取所有可用命令。
 * @returns {$CancellablePromise<model$0.CmdPaletteItem[]>}
 */
export function GetOpenCodeCommands() {
    return $Call.ByID(2770937016).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * GetProjectTree 获取项目→目录→会话的树形结构 JSON。
 * @param {string} knownDirs
 * @returns {$CancellablePromise<string>}
 */
export function GetProjectTree(knownDirs) {
    return $Call.ByID(1878567804, knownDirs);
}

/**
 * GetProviderConfigPath 返回供应商配置文件路径。
 * @returns {$CancellablePromise<string>}
 */
export function GetProviderConfigPath() {
    return $Call.ByID(2693012447);
}

/**
 * GetProviders 获取所有供应商配置。
 * @returns {$CancellablePromise<model$0.ProviderInfo[]>}
 */
export function GetProviders() {
    return $Call.ByID(2525123639).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * GetSessions 获取最近 15 个 OpenCode 会话记录。
 * @returns {$CancellablePromise<model$0.SessionInfo[]>}
 */
export function GetSessions() {
    return $Call.ByID(3316780542).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * GetSkills 返回所有技能及其在各平台的链接状态。
 * @returns {$CancellablePromise<model$0.SkillInfo[]>}
 */
export function GetSkills() {
    return $Call.ByID(1520668053).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * GetSourceDir 返回技能源目录路径。
 * @returns {$CancellablePromise<string>}
 */
export function GetSourceDir() {
    return $Call.ByID(25163249);
}

/**
 * GetStats 返回统计信息。
 * @returns {$CancellablePromise<model$0.Stats>}
 */
export function GetStats() {
    return $Call.ByID(2859423874).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * GetWebStatus 返回当前 web 服务状态。
 * @param {string} hostname
 * @param {number} port
 * @returns {$CancellablePromise<model$0.WebResult>}
 */
export function GetWebStatus(hostname, port) {
    return $Call.ByID(1108731257, hostname, port).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * LaunchWindowsTerminal 在外部终端中打开 opencode。
 * @param {string} mode
 * @param {string} webURL
 * @param {string} dir
 * @returns {$CancellablePromise<model$0.WebResult>}
 */
export function LaunchWindowsTerminal(mode, webURL, dir) {
    return $Call.ByID(2591073375, mode, webURL, dir).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * OpenCodeAPI 代理访问本机 opencode serve API。
 * @param {string} method
 * @param {string} path
 * @param {string} body
 * @returns {$CancellablePromise<model$0.APIResult>}
 */
export function OpenCodeAPI(method, path, body) {
    return $Call.ByID(4008055560, method, path, body).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * OpenDir 在文件资源管理器中打开指定目录。
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function OpenDir(path) {
    return $Call.ByID(288356608, path);
}

/**
 * OpenDirectoryDialog 打开目录选择对话框。
 * @returns {$CancellablePromise<string>}
 */
export function OpenDirectoryDialog() {
    return $Call.ByID(1188724780);
}

/**
 * ReadSkillContent 读取技能 SKILL.md 内容。
 * @param {string} skillPath
 * @returns {$CancellablePromise<string>}
 */
export function ReadSkillContent(skillPath) {
    return $Call.ByID(483867471, skillPath);
}

/**
 * Refresh 重新扫描技能目录并刷新状态。
 * @returns {$CancellablePromise<void>}
 */
export function Refresh() {
    return $Call.ByID(2576512028);
}

/**
 * RefreshAvailableModels 强制刷新模型列表缓存。
 * @returns {$CancellablePromise<string[]>}
 */
export function RefreshAvailableModels() {
    return $Call.ByID(3035361405).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * RejectQuestion 忽略 question 工具调用。
 * @param {string} sessionID
 * @returns {$CancellablePromise<model$0.APIResult>}
 */
export function RejectQuestion(sessionID) {
    return $Call.ByID(4071089598, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * SaveFullConfig 将前端修改后的完整 JSON 字符串直接写入文件。
 * @param {string} jsonStr
 * @returns {$CancellablePromise<model$0.SaveResult>}
 */
export function SaveFullConfig(jsonStr) {
    return $Call.ByID(1578594615, jsonStr).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * SaveProvider 保存供应商配置。
 * @param {model$0.ProviderSave} ps
 * @returns {$CancellablePromise<model$0.SaveResult>}
 */
export function SaveProvider(ps) {
    return $Call.ByID(1885182733, ps).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * SaveSkillContent 保存技能 SKILL.md 内容。
 * @param {string} skillPath
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function SaveSkillContent(skillPath, content) {
    return $Call.ByID(2284615434, skillPath, content);
}

/**
 * StartOpenCodeEvents 连接 opencode 全局 SSE。
 * @returns {$CancellablePromise<model$0.APIResult>}
 */
export function StartOpenCodeEvents() {
    return $Call.ByID(3535731511).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * StartOpenCodeWeb 启动 opencode serve。
 * @param {number} port
 * @param {string} hostname
 * @param {model$0.ProxyConfig} proxy
 * @returns {$CancellablePromise<model$0.WebResult>}
 */
export function StartOpenCodeWeb(port, hostname, proxy) {
    return $Call.ByID(595414420, port, hostname, proxy).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * StopOpenCodeEvents 停止 SSE 转发。
 * @returns {$CancellablePromise<model$0.APIResult>}
 */
export function StopOpenCodeEvents() {
    return $Call.ByID(2369516441).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * StopOpenCodeWeb 停止 opencode web 服务。
 * @returns {$CancellablePromise<model$0.WebResult>}
 */
export function StopOpenCodeWeb() {
    return $Call.ByID(888045870).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * ToggleSkill 切换技能链接状态。
 * @param {string} skillPath
 * @param {string} skillName
 * @param {boolean} enable
 * @returns {$CancellablePromise<model$0.ToggleResult>}
 */
export function ToggleSkill(skillPath, skillName, enable) {
    return $Call.ByID(2106209646, skillPath, skillName, enable).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * UpdateModels 批量更新模型配置并保存到 JSONC 文件。
 * @param {model$0.ModelEntry[]} entries
 * @returns {$CancellablePromise<model$0.ModelSaveResult>}
 */
export function UpdateModels(entries) {
    return $Call.ByID(1719430574, entries).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = model$0.ModelSaveResult.createFrom;
const $$createType1 = model$0.APIResult.createFrom;
const $$createType2 = model$0.SaveResult.createFrom;
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = model$0.CmdGroup.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = model$0.ModelEntry.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = model$0.CmdPaletteItem.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = model$0.ProviderInfo.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = model$0.SessionInfo.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = model$0.SkillInfo.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = model$0.Stats.createFrom;
const $$createType17 = model$0.WebResult.createFrom;
const $$createType18 = model$0.ToggleResult.createFrom;
