// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAvailableModels() {
  return window['go']['main']['App']['GetAvailableModels']();
}

export function GetCommands() {
  return window['go']['main']['App']['GetCommands']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetModelConfig() {
  return window['go']['main']['App']['GetModelConfig']();
}

export function GetSkills() {
  return window['go']['main']['App']['GetSkills']();
}

export function GetSourceDir() {
  return window['go']['main']['App']['GetSourceDir']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetTargets() {
  return window['go']['main']['App']['GetTargets']();
}

export function OpenDir(arg1) {
  return window['go']['main']['App']['OpenDir'](arg1);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function Refresh() {
  return window['go']['main']['App']['Refresh']();
}

export function RefreshAvailableModels() {
  return window['go']['main']['App']['RefreshAvailableModels']();
}

export function RunOpenCode(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RunOpenCode'](arg1, arg2, arg3, arg4, arg5);
}

export function ToggleAllSkills(arg1, arg2) {
  return window['go']['main']['App']['ToggleAllSkills'](arg1, arg2);
}

export function ToggleSkill(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleSkill'](arg1, arg2, arg3);
}

export function UpdateModels(arg1) {
  return window['go']['main']['App']['UpdateModels'](arg1);
}
