// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAvailableModels():Promise<Array<string>>;

export function GetConfigPath():Promise<string>;

export function GetModelConfig():Promise<Array<main.ModelEntry>>;

export function GetSkills():Promise<Array<main.SkillInfo>>;

export function GetSourceDir():Promise<string>;

export function GetStats():Promise<main.Stats>;

export function GetTargets():Promise<Array<main.TargetInfo>>;

export function OpenDir(arg1:string):Promise<void>;

export function Refresh():Promise<void>;

export function ToggleAllSkills(arg1:string,arg2:boolean):Promise<main.BatchResult>;

export function ToggleSkill(arg1:string,arg2:string,arg3:boolean):Promise<main.ToggleResult>;

export function UpdateModels(arg1:Array<main.ModelEntry>):Promise<main.ModelSaveResult>;
