// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddModelEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddModelEntry'](arg1, arg2, arg3);
}

export function AddModelType(arg1) {
  return window['go']['main']['App']['AddModelType'](arg1);
}

export function AnswerQuestion(arg1, arg2) {
  return window['go']['main']['App']['AnswerQuestion'](arg1, arg2);
}

export function CreateSession(arg1) {
  return window['go']['main']['App']['CreateSession'](arg1);
}

export function DeleteModelEntry(arg1, arg2) {
  return window['go']['main']['App']['DeleteModelEntry'](arg1, arg2);
}

export function DeleteModelType(arg1) {
  return window['go']['main']['App']['DeleteModelType'](arg1);
}

export function DeleteProvider(arg1) {
  return window['go']['main']['App']['DeleteProvider'](arg1);
}

export function GetAvailableModels() {
  return window['go']['main']['App']['GetAvailableModels']();
}

export function GetCommands() {
  return window['go']['main']['App']['GetCommands']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetFullConfig() {
  return window['go']['main']['App']['GetFullConfig']();
}

export function GetModelConfig() {
  return window['go']['main']['App']['GetModelConfig']();
}

export function GetOpenCodeCommands() {
  return window['go']['main']['App']['GetOpenCodeCommands']();
}

export function GetProjectTree(arg1) {
  return window['go']['main']['App']['GetProjectTree'](arg1);
}

export function GetProviderConfigPath() {
  return window['go']['main']['App']['GetProviderConfigPath']();
}

export function GetProviders() {
  return window['go']['main']['App']['GetProviders']();
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetSkills() {
  return window['go']['main']['App']['GetSkills']();
}

export function GetSourceDir() {
  return window['go']['main']['App']['GetSourceDir']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetWebStatus(arg1, arg2) {
  return window['go']['main']['App']['GetWebStatus'](arg1, arg2);
}

export function LaunchWindowsTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['LaunchWindowsTerminal'](arg1, arg2, arg3);
}

export function OpenCodeAPI(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenCodeAPI'](arg1, arg2, arg3);
}

export function OpenDir(arg1) {
  return window['go']['main']['App']['OpenDir'](arg1);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function ReadSkillContent(arg1) {
  return window['go']['main']['App']['ReadSkillContent'](arg1);
}

export function Refresh() {
  return window['go']['main']['App']['Refresh']();
}

export function RefreshAvailableModels() {
  return window['go']['main']['App']['RefreshAvailableModels']();
}

export function RejectQuestion(arg1) {
  return window['go']['main']['App']['RejectQuestion'](arg1);
}

export function SaveFullConfig(arg1) {
  return window['go']['main']['App']['SaveFullConfig'](arg1);
}

export function SaveProvider(arg1) {
  return window['go']['main']['App']['SaveProvider'](arg1);
}

export function SaveSkillContent(arg1, arg2) {
  return window['go']['main']['App']['SaveSkillContent'](arg1, arg2);
}

export function StartOpenCodeEvents() {
  return window['go']['main']['App']['StartOpenCodeEvents']();
}

export function StartOpenCodeWeb(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartOpenCodeWeb'](arg1, arg2, arg3);
}

export function StopOpenCodeEvents() {
  return window['go']['main']['App']['StopOpenCodeEvents']();
}

export function StopOpenCodeWeb() {
  return window['go']['main']['App']['StopOpenCodeWeb']();
}

export function ToggleSkill(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleSkill'](arg1, arg2, arg3);
}

export function UpdateModels(arg1) {
  return window['go']['main']['App']['UpdateModels'](arg1);
}
