// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddModelEntry(arg1:string,arg2:string,arg3:string):Promise<main.ModelSaveResult>;

export function DeleteModelEntry(arg1:string,arg2:string):Promise<main.ModelSaveResult>;

export function DeleteProvider(arg1:string):Promise<main.SaveResult>;

export function GetAvailableModels():Promise<Array<string>>;

export function GetCommands():Promise<Array<main.CmdGroup>>;

export function GetConfigPath():Promise<string>;

export function GetFullConfig():Promise<string>;

export function GetModelConfig():Promise<Array<main.ModelEntry>>;

export function GetProviderConfigPath():Promise<string>;

export function GetProviders():Promise<Array<main.ProviderInfo>>;

export function GetSessions():Promise<Array<main.SessionInfo>>;

export function GetSkills():Promise<Array<main.SkillInfo>>;

export function GetSourceDir():Promise<string>;

export function GetStats():Promise<main.Stats>;

export function GetTargets():Promise<Array<main.TargetInfo>>;

export function OpenDir(arg1:string):Promise<void>;

export function OpenDirectoryDialog():Promise<string>;

export function Refresh():Promise<void>;

export function RefreshAvailableModels():Promise<Array<string>>;

export function ResizeTerminal(arg1:number,arg2:number):Promise<void>;

export function RunOpenCode(arg1:string,arg2:boolean):Promise<void>;

export function SaveFullConfig(arg1:string):Promise<main.SaveResult>;

export function SaveProvider(arg1:main.ProviderSave):Promise<main.SaveResult>;

export function StartTerminal():Promise<string>;

export function TerminalWrite(arg1:string):Promise<void>;

export function ToggleAllSkills(arg1:string,arg2:boolean):Promise<main.BatchResult>;

export function ToggleSkill(arg1:string,arg2:string,arg3:boolean):Promise<main.ToggleResult>;

export function UpdateModels(arg1:Array<main.ModelEntry>):Promise<main.ModelSaveResult>;
